# Generated by Django 4.0.6 on 2022-07-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=400, null=True)),
                ('check_in_date', models.DateTimeField(auto_now_add=True)),
                ('picked', models.BooleanField(default=False)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('clothes_condition', models.CharField(choices=[('GOOD', 'GOOD'), ('BAD', 'BAD')], default='GOOD', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'CASH'), ('MPESA', 'MPESA'), ('SWIPE', 'SWIPE')], default='CASH', max_length=20)),
            ],
        ),
    ]
