# Generated by Django 4.0.6 on 2022-07-29 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_client_order_no_client_served_by_client_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='order_no',
        ),
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
