# Generated by Django 4.0.6 on 2022-07-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_client_check_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
