# Generated by Django 4.0.6 on 2022-07-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_client_check_in_time_client_check_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
