# Generated by Django 4.0.6 on 2022-07-25 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_client_check_in_time_alter_client_check_in_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clothes_condition',
        ),
    ]
