# Generated by Django 4.0.6 on 2022-07-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_client_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
