# Generated by Django 4.0.6 on 2022-07-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_remove_client_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
