# Generated by Django 4.0.6 on 2022-07-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_alter_client_check_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('MPESA', 'MPESA'), ('SWIPE', 'SWIPE')], default='CASH', max_length=20, null=True),
        ),
    ]
